### ISSUE TITLE
PHP notice "Undefined property: Less_Tree_Variable::$value" for files imported through variables

### ISSUE THREAD

**Issue by czirkoszoltan** [wikimedia/less.php#29]
When a file is imported, and the filename is specified through a less variable, a PHP notice is issued:

```
PHP Notice:  Undefined property: Less_Tree_Variable::$value
  in [...]/Less/Tree/Import.php on line 108
```

The code line in question is:

```
} else if ($this->path instanceof Less_Tree_URL) {
	$path = $this->path->value->value;
}else{
```

Still, the import works.

Test case: [import-notice-test-case.zip](https://github.com/wikimedia/less.php/files/4241830/import-notice-test-case.zip)

This might be related to #27 also dealing with imports.

**Comment by mrtuvn** [comment]
Maybe related but i got relate issue when use get-unit function
Used less 2.3.1 with php 7.3.3

error evaluating function `get-unit` Notice: Undefined property: Less_Tree_Keyword::$unit in /var/www/html/vendor/wikimedia/less.php/lib/Less/Functions.php

**Comment by Krinkle** [comment]
Thanks @czirkoszoltan. I was able to reproduce this and narrow it down to any kind of import that involves a variable:

```less
// a.less
@filetoimport: "b.less";

@import url(@filetoimport);
```
```less
// b.less
body { margin: 0; }
```
```
$ bin/lessc a.less
PHP Notice:  Undefined property: Less_Tree_Variable::$value in less.php/lib/Less/Tree/Import.php on line 110

body {
  margin: 0;
}
```

The issue happens in `Less_Tree_Import::getPath()`, but the import indeed works fine regardless of this issue. This is because `Import::getPath()` is expected to return `string|null` and the undefined property ends up returning null, which is exaclty what it should do otherwise. The null value is then tolerated everywhere during this first pass until the second pass where the `value` has been defined during variable expansion, and then it works fine as intended.

The code in question mirrors the less.js code exactly, where I suspect the same issue exists. However, in JavaScript there are no warnings for accessing the first level of undefined properties, so it behaves as intended there without warnings.
