### ISSUE TITLE
It would be nice, if css variables will pass as is

### ISSUE THREAD

**Issue by ddetyuk** [wikimedia/less.php#44]
code:

>
```
$parser = new \Less_Parser(['compress' => false, 'strictMath' => false]);
$parser->parse("
	:root {
	  --css-variable: 1;
	}
	.a {
	  animation-iteration-count: calc(var(--css-variable) * 2);
	}			
");
```
thrown exception:

> Operation on an invalid type

**Comment by ezequielalba** [comment]
I am having this exact issue with a Magento 2 compilation. Did you find a hack or fix to use CSS variables in your less files? @ddetyuk

**Comment by Krinkle** [comment]
This matches the behaviour of the official Less.js 2.x parser. Try in [this demo](http://ecomfe.github.io/est/fiddle/#version=2.7.3&autoprefix=false&est=false&autorun=false) for example.

The error happens because `calc()` is treated here as a Less compilation function, instead of as a CSS value to preserve for the browser to process instead. You can make this work by using [Less escaping](https://lesscss.org/#escaping), like so:

```less
.a {
	  animation-iteration-count: ~"calc(var(--css-variable) * 2)";
}
```

In Less.js 3.0, the compiler was improved to recognise `var()` syntax and pass it through to the browser. However, we don't yet support most of the Less.js 3.x syntax in Less.php.
