### ISSUE TITLE
Fix and make a release that works on PHP 8.0

### ISSUE THREAD

**Issue by dleffler** [wikimedia/less.php#50]
Under PHP v8.0.0
Deprecated: Required parameter $rules follows optional parameter $value in K:\UwAmp\www\exp2\external\less.php\lib\Less\Tree\Directive.php on line 20

Currently
	public function __construct($name, $value = null, $rules, $index = null, $currentFileInfo = null, $debugInfo = null ){

Possible fix
	public function __construct($name = null, $value = null, $rules = null, $index = null, $currentFileInfo = null, $debugInfo = null ){

**Comment by xmorave2** [comment]
Fixed in #34

**Comment by jdforrester** [comment]
I've made a start with another fix in #53.

**Comment by jdforrester** [comment]
Release v3.1.0 is now out on packagist.org etc.

**Comment by sgiehl** [comment]
@jdforrester  Thanks for the release. Is there any specific reason v3 requires PHP 7.2.9. 
We're using the lib in a project requiring PHP 7.2.5 and we can't easily adjust the requirement without a major release, which won't happen soon. Wondering if there might be any issue when using it on PHP 7.2.5 nevertheless 🤔

**Comment by jdforrester** [comment]
Hey there,

Sorry about that. We bumped MediaWiki's dependency on PHP 7.2.x to 7.2.9 to work around a few segfaults in PHP that got fixed upstream, and so as general practice we apply that to all our libraries, rather than pretend that we thing 7.2.0 is safe, and that's what I did in 28baca4fb84da050f8d7f625230753d5ca461bca. (Note that we ran into another segfault and had to raise it again to 7.2.22 for https://phabricator.wikimedia.org/T228346.)

In practice, I imagine the segfaults aren't likely to be an issue for your library either, so you can bypass the restriction if you need to.

**Comment by dleffler** [comment]
I'm able to use the current version 3.1.0 on php v5.6 with only a change to the Version,php file removing the 'public' from the 3 const lines
