### ISSUE TITLE
Escaped calc inside Recursive Mixins

### ISSUE THREAD

**Issue by jonalange** [wikimedia/less.php#66]
I use version 2.5.3 off less and test it with this compiler: http://ecomfe.github.io/est/fiddle/#version=2.5.3&autoprefix=false

In this version the calc is pretty strict and throws all my units all over the place, so I escape it like this:
`width: calc(100vw - 30px);` becomes this: `width: calc(~"100vw - 30px");`
It is working, but in combination with Recursive Mixins it gives me errors.

My code:
```
        .generate_rows_tablet_m_4 (@i , @n) when (@i < 41) {
            .start-row-m-@{i}.row-m-4 {
                height: calc(~"100vw - 15px") !important;
                top: calc(@n * (~"50vw - 7.5px")) !important;
            }

            .generate_rows_tablet_m_4(@i + 1, @i * 0.5)
        }

        .generate_rows_tablet_m_4(2, 0.5);
```

The compiler tells me that a `)` is missing in line 4.
When I remove the escape `~" "` the error is gone and it compiles. Although my calculation is then wrong.

How can I fix this? I still want to use the "correct" calculation.

**Comment by Krinkle** [comment]
Hi @jonalange,

This is the issue tracker for the PHP package `wikimedia/less.php`, which is the PHP version of the official [Less.js](https://lesscss.org/) parser, which has an issue tracker at <>.

It seems that when I turn off the "est" feature in your example, the syntax is still invalid. As such, it seems wikimedia/less.php is following the standard in terms of considering this as invalid syntax.

I will take one attempt to help you, but for further with Less in general please refer to the [official Less](https://github.com/less/less.js) issue tracker or [their chat room](https://github.com/less/less.js#readme).

The compiler error comes from the issue that the Less version of `calc()` only supports simple expressions. It does not support nested expressions with their own parenthesis. You are in the right direction by using string escapes, however, the code you currently have still leaves the parenthesis outside the escaped portion, which means Less is still being asked to compile them (and it cannot do that).

```diff
-  top: calc(@n * (~"50vw - 7.5px")) !important;
+  top: calc(@n * ~"(50vw - 7.5px)") !important;
```

The above works in Less 3.5 compilers and later. Alternatively, you can also escape the entire calc function call and instead use string interpolation for the variable `@{u}` instead of `@u` when inside of an escaped string:

```diff
-  top: calc(@n * (~"50vw - 7.5px")) !important;
+  top: ~"calc(@{n} * (50vw - 7.5px))" !important;
```

The above also works in all Less 2.x and 3.x versions.
