### ISSUE TITLE
 Imported files get optimized incorrectly

### ISSUE THREAD

**Issue by jdlrobson** [wikimedia/less.php#69]
Create the following 2 files

1) test.less:
```
@media screen {
    body:not( .skin--responsive ) {
        @import 'test-import.less';
    }

    body.skin--responsive {
        @media ( min-width: 551px ) {
            @import 'test-import.less';
        }
    }
}
```

2) test-import.less:
```
a {
    color: red;
}
```

Run
```
<?php
require_once 'lib/Less/Autoloader.php';
Less_Autoloader::register();
$parser = new Less_Parser();
$parser->parseFile( 'test.less' );
$css = $parser->getCss();
echo $css;

```

Expected:

The LESS compiler should produce:
```
@media screen {
  body:not( .skin--responsive ) a {
    color: red;
  }
}
@media screen and (min-width: 551px) {
  body.skin--responsive a {
    color: red;
  }
}
```

Actual:

```
@media screen {
  body:not( .skin--responsive ) a {
    color: red;
  }
}
```

**Comment by DannyS712** [comment]
Likely cause https://github.com/wikimedia/less.php/blob/020c632e0facf1094d3c999162a04de14b062e22/lib/Less/Tree/Import.php#L160 - imports appear to be skipped on subsequent imports of the same file.

**Comment by Krinkle** [comment]
For future reference, the use case this issue was filed is [change 701445](https://gerrit.wikimedia.org/r/c/mediawiki/skins/MonoBook/+/701445) for the MonoBook skin.

------

As I understand it, the current behaviour is the standard and expected behaviour in accordance with the upstream Less documentation and reference implementation from <http://lesscss.org/>.

You can read how `@import` is meant to work at <https://lesscss.org/features/>, as well as test cases such as https://github.com/less/less.js/commit/d9f929a0633 that mandate and verify this behaviour. I believe various MediaWiki code in production also depends a fair bit already, but perhaps in ways that are less obvious. For example, one might be importing something with a common dependency that was already imported before.

From a developer experience and performance perspective, one would probably want to try to approach this differently at a higher-level since the current structure is not compatible with how CSS work in browsers. It's not a bad way to think about it, but the web just approaches it differently. I'm sure there's a way it can work that won't feel like a compromise once you find it.

Alternatively, the documentation also mentions a `@import (multiple)` option for when you are able to accept the consequences and bypass the deduplication guard. This option is also supported and tested for in Wikimedia's implementation, and even used [in production code](https://codesearch.wmcloud.org/deployed/?q=%40import.%2Bmultiple&i=nope&files=less%24&excludeFiles=&repos=).
