### ISSUE TITLE
Got error when use clamp function css

### ISSUE THREAD

**Issue by mrtuvn** [wikimedia/less.php#78]
error evaluating function `clamp` Notice: Object of class Less_Tree_Dimension could not be converted to int in /var/www/html/vendor/wikimedia/less.php/lib/Less/Functions.php on line 33

https://developer.mozilla.org/en-US/docs/Web/CSS/clamp

**Comment by dimasch** [comment]
The same.

**Comment by jamie-selesti** [comment]
Same here, we use this library as its bundled with Magento's official framework

**Comment by mrtuvn** [comment]
Also I can't use min or max function too
https://developer.mozilla.org/en-US/docs/Web/CSS/min

**Comment by Gappa** [comment]
One way to get it working is to escape the whole function:

- `property: ~"clamp(10px, 5vw, 100px)";`
- `property: ~"clamp(var(--css-variable), 5vw, 100px)";`
- `property: ~"clamp(@{lessVariable}, 5vw, 100px)";`

**Comment by Krinkle** [comment]
I supected that this was due to upstream only supporting it after less 2.5.3, but looks like it worked upstream on the current reference version as well:

<http://lesscss.org/less-preview/#eyJjb2RlIjoieCB7XG4gIHdpZHRoOiBjbGFtcCgxMHB4LCA1dncsIDEwMHB4KTtcbn0iLCJhY3RpdmVWZXJzaW9uIjoiMi41LjMifQ==>

Thus confirming as bug rather than feature request. (I know it feels like a bug either way, but less.php aims to offer parity with less.js, so matching behaviour would be expected.)

**Comment by mrtuvn** [comment]
just for report another fail while some works. I think we should also add label Feature for all these cases

container queries also broken 

```less
@container some_name () {

}
```

```

**Comment by Krinkle** [comment]
Imported to our own issue tracker, fix in progress: <https://phabricator.wikimedia.org/T363728>.

**Comment by Krinkle** [comment]
Released in v4.4.0. https://github.com/wikimedia/less.php/blob/v4.4.0/CHANGES.md
