### ISSUE TITLE
Import from google font

### ISSUE THREAD

**Issue by eydun** [wikimedia/less.php#92]
Thank you for building this great project.

I have this in my source.less.
```
@import url('https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i');
```

I would expect it would compile to
```
/* cyrillic-ext */
@font-face {
  font-family: 'Open Sans';
  font-style: italic;
  font-weight: 300;
  font-stretch: 100%;
  src: url(https://fonts.gstatic.com/s/opensans/v34/memtYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWqWtE6F15M.woff2) format('woff2');
  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
}
....
```

But it does not happen. 

Or is this not possible?

**Comment by Krinkle** [comment]
Use of Google Fonts API is supported with less.php and should work correctly. Can you confirm that the `@import` statement is preserved and that your web page is able to load and display the font correctly?

For security reasons, remote content will not be included within the compiled output because Less is effectively an executable language. (It would also be missing deterministic tracking of updates or cache invalidations.)

This matches the behaviour of upstream Less.JS, e.g. as checked at <http://ecomfe.github.io/est/fiddle/#version=2.5.3&autoprefix=false&est=false&autorun=false>.

**Comment by Krinkle** [comment]
If you're interested in optimal performance, I recommend storing the font file directly in your own code repository, along your CSS files, and reference the file form a `@font-face` rule directly. This is generally even faster than using a CDN.

About use of CDNs and how in 2023 it is basically worse for performance, security, uptime, and privacy. There is no caching benefits because browsers already store one copy for every referral domain separately
* https://gomakethings.com/cdn-caching-isnt-the-performance-boost-it-used-to-be/
* https://csswizardry.com/2019/05/self-host-your-static-assets/ — <https://news.ycombinator.com/item?id=30569528>
* https://calendar.perfplanet.com/2019/self-hosting-third-party-resources-the-good-the-bad-and-the-ugly/

See also:
* https://css-tricks.com/dont-just-copy-the-font-face-out-of-google-fonts-urls/
* https://gwfh.mranftl.com/fonts
* https://blog.logrocket.com/self-hosted-fonts-vs-google-fonts-api/
* https://fonts.google.com/knowledge/using_type/self_hosting_web_fonts

**Comment by eydun** [comment]
Thank you for the prompt and quality answer, much appreciated!

> . Can you confirm that the @import statement is preserved and that your web page is able to load and display the font correctly?

Yes, I can confirm that.

I tested this with CodeKit, which did include the remote font-face definitions from fonts.googleapis.com, so therefore I assumed that less.php should do the same. But you correct about the security-concerns with including remote content, so I agree with the less.php-solution. 

Thank you for the performance-considerations regarding use of CDN. I will host the fonts locally.

Thanks!
